version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - nextex_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: main_db
      MYSQL_USER: nextex
      MYSQL_PASSWORD: yes
    ports:
      - "3333:3306"
  
  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ../backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ../frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  nextex_data:
  frontend_node_modules: